import mongoose from 'mongoose';
import { POINT_TYPES, ERROR_TYPES } from '../domain/stats.js';

const { Schema } = mongoose;

/**
 * An atomic scored rally. This collection is the append-only source of truth
 * for scores and for all derived statistics.
 *
 * Idempotency: every event carries a clientEventId generated by the scorer. A
 * unique (match, clientEventId) index means a replayed event from the offline
 * outbox can never create a duplicate point.
 *
 * Undo: instead of hard-deleting, an undone event is marked voided=true and
 * excluded from scoring/stats. This preserves an honest audit trail of the
 * match while keeping the running score correct.
 */
const rallyEventSchema = new Schema(
  {
    match: { type: Schema.Types.ObjectId, ref: 'Match', required: true, index: true },
    tournament: { type: Schema.Types.ObjectId, ref: 'Tournament', required: true, index: true },
    clientEventId: { type: String, required: true },
    seq: { type: Number, required: true }, // server-assigned order within the match

    setNumber: { type: Number, required: true },
    winner: { type: String, enum: ['A', 'B'], required: true }, // team awarded the point
    pointType: { type: String, enum: Object.values(POINT_TYPES), required: true },

    // Attribution (all optional — scoring is never blocked on it).
    player: { type: Schema.Types.ObjectId, ref: 'Player', default: null }, // scorer/attacker/blocker/server
    assistPlayer: { type: Schema.Types.ObjectId, ref: 'Player', default: null },
    errorType: { type: String, enum: [...Object.values(ERROR_TYPES), null], default: null },
    errorPlayer: { type: Schema.Types.ObjectId, ref: 'Player', default: null },
    digPlayer: { type: Schema.Types.ObjectId, ref: 'Player', default: null },
    receptionPlayer: { type: Schema.Types.ObjectId, ref: 'Player', default: null },
    note: { type: String, default: null },

    // Score snapshot AFTER this rally (within its set), for the public timeline.
    scoreAfter: {
      a: { type: Number, required: true },
      b: { type: Number, required: true },
    },

    voided: { type: Boolean, default: false, index: true },
    createdBy: { type: Schema.Types.ObjectId, ref: 'User', default: null },
  },
  { timestamps: true }
);

rallyEventSchema.index({ match: 1, clientEventId: 1 }, { unique: true });
rallyEventSchema.index({ match: 1, seq: 1 });

export const RallyEvent = mongoose.model('RallyEvent', rallyEventSchema);
